defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:  
  output_subdir: null  
  run:  
    dir: .

dataset:
  # path to selected basins file
  selected_basins: "../data/selected_basins.csv"

  # the dataset directory
  path: "../data/CAMELS_KZ"
  # directory name for dynamic features for each basin (.nc)
  # required for `neuralhydrology`
  time_series: "time_series"

  # which features to prepare as autoregressive
  autoregressive_features:
    - level
    - discharge

  # cathcment attributes
  catchment_attributes:
    # directory for cathcment attributes
    path: "attributes"
    # the attributes splitted into files
    attributes:
      climate:
        name: "camels_clim.csv"
        features:
          - p_mean
          - pet_mean
          - p_seasonality
          - frac_snow_daily
          - aridity
          - high_prec_freq
          - high_prec_dur
          - low_prec_freq
          - low_prec_dur

      soil:
        name: "camels_soil.csv"
        features:
          - soil_conductivity
          - max_water_content
          - sand_frac
          - silt_frac
          - clay_frac

      topology:
        name: "camels_topo.csv"
        features:
          - elev_mean
          - slope_mean
          - area_gages2

      vegetation:
        name: "camels_vege.csv"
        features:
          - forest_frac
          - lai_max
          - lai_diff
          - gvf_max
          - gvf_diff

  # directory name for dynamic features for each basin (.csv)
  forcing: "mean_basin_forcing"
  streamflow: "streamflow"

  # Google Earth Engine
  gee:
    # path to the directory
    path: "../data/GEE"
    catchment_attributes:
      path: "attributes"
    forcing:
      # path for solar radiation for each basin
      - srad

# KazHydroMet config for parser
kazhydromet:
  # directory for dataset
  path: "../data/kazhydromet"
  # directory for meteo stations
  meteo: "basin_forcing"
  # directory for hydro stations
  hydro: "streamflow"
