
lai_band: 'Lai_500m'
forest_band: 'Percent_Tree_Cover'
green_band: 'NDVI'
zipped_shapefiles_dir: "../zipped_files"
start_date: '2000-02-18'
end_date: '2023-01-01'
asset_folder: "projects/virtual-rarity-426212-p6/assets/shapefiles" # the folder storing  
                                                                    # the shapefiles in zip format (shp, dbf, ...)
meteo_files: "/Users/abzal/Desktop/issai-srp/KazDataset/meteo"  # folder containing all meteo files in txt format                                                   